# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# update bash configuration
alias bps="source ~/.bashrc && source ~/.bash_profile"

#---------------------------------------
# CREATING SSH KEY

# generate ssh key
# sshkg example@domain.com
sshkg() {
    ssh-keygen -t rsa -b 4096 -C $1
}

# start the ssh-agent in the background
alias sshas="eval $(ssh-agent -s)"

# add a key to an agent
# ssh-agent ~/.ssh/id_rsa
sshaa() {
    ssh-agent $1
}
#---------------------------------------
